import { mkdir, readdir, rm, rename } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import type { IconDefinition, IconGlyph, IconVariant } from '../src/types.js';
import { parseSvg } from './svg.js';

const root = resolve(import.meta.dir, '..');
const upstream = join(root, 'node_modules/@fluentui/svg-icons');
const destination = join(root, 'src/generated');
const staging = join(root, 'src/.generated-staging');
const upstreamPackage = await Bun.file(join(upstream, 'package.json')).json();
const sourceFiles = (await readdir(join(upstream, 'icons'))).filter((name) => /_(regular|filled|color)\.svg$/.test(name)).sort();
if (sourceFiles.length === 0) throw new Error('No Fluent SVGs found. Run bun install first.');

const families = new Map<string, IconGlyph[]>();
const digest = new Bun.CryptoHasher('sha256');
digest.update(upstreamPackage.version);
// The parser is deliberately part of the fingerprint so parser edits regenerate outputs.
digest.update(await Bun.file(join(root, 'scripts/svg.ts')).text());
digest.update(await Bun.file(join(root, 'scripts/svg-color.ts')).text());
digest.update(await Bun.file(join(root, 'src/svg-tree.ts')).text());
digest.update(await Bun.file(import.meta.filename).text());
const batchSize = 128;
for (let offset = 0; offset < sourceFiles.length; offset += batchSize) {
  const batch = sourceFiles.slice(offset, offset + batchSize);
  const contents = await Promise.all(batch.map((filename) => Bun.file(join(upstream, 'icons', filename)).text()));
  for (const [index, filename] of batch.entries()) {
    const match = filename.match(/^([a-z0-9_]+)_(\d+)_(regular|filled|color)\.svg$/);
    if (!match) throw new Error(`Unexpected filename: ${filename}`);
    const name = match[1]!.replaceAll('_', '-');
    const glyphs = families.get(name) ?? [];
    const glyph = parseSvg(contents[index]!, Number(match[2]), match[3] as IconVariant, filename);
    if (glyphs.some((item) => item.size === glyph.size && item.variant === glyph.variant)) throw new Error(`Duplicate glyph: ${filename}`);
    glyphs.push(glyph);
    families.set(name, glyphs);
    digest.update(filename).update(contents[index]!);
  }
}
const fingerprint = digest.digest('hex');
const names = [...families.keys()].sort();
const readmePath = join(root, 'README.md');
if (await Bun.file(readmePath).exists()) {
  const readme = await Bun.file(readmePath).text();
  const stats = `<!-- icon-stats:start -->\n**${names.length.toLocaleString('en-US')} families / ${sourceFiles.length.toLocaleString('en-US')} designs**, generated from \`@fluentui/svg-icons\` ${upstreamPackage.version}.\n<!-- icon-stats:end -->`;
  const updated = readme.replace(/<!-- icon-stats:start -->[\s\S]*?<!-- icon-stats:end -->/, stats);
  if (updated !== readme) await Bun.write(readmePath, updated);
}
const previous = await Bun.file(join(destination, 'metadata.json')).json().catch(() => null);
// Validate the generated file inventory as well as the source fingerprint.
const inventory = await readdir(join(destination, 'icons')).catch(() => [] as string[]);
const requiredFiles = ['catalog.js', 'catalog.d.ts', 'loaders.js', 'loaders.d.ts', 'names.js', 'names.d.ts'];
const complete = inventory.length === names.length * 2 && names.every((name) => inventory.includes(`${name}.js`) && inventory.includes(`${name}.d.ts`)) &&
  (await Promise.all(requiredFiles.map((name) => Bun.file(join(destination, name)).exists()))).every(Boolean);
if (previous?.fingerprint === fingerprint && complete && !process.argv.includes('--force')) {
  console.log(`Icons up to date: ${names.length.toLocaleString()} families, ${sourceFiles.length.toLocaleString()} glyphs (Fluent ${upstreamPackage.version}).`);
  process.exit(0);
}

// Both targets are fixed children of this project, never user-provided paths.
await rm(staging, { recursive: true, force: true });
await mkdir(join(staging, 'icons'), { recursive: true });
const header = '// Generated by bun run generate. Do not edit. Fluent System Icons © Microsoft. MIT license.\n';
const catalog: { name: string; exportName: string; sizes: number[]; variants: string[] }[] = [];
for (let offset = 0; offset < names.length; offset += batchSize) {
  await Promise.all(names.slice(offset, offset + batchSize).map(async (name) => {
    const glyphs = families.get(name)!.sort((a, b) => a.size - b.size || a.variant.localeCompare(b.variant));
    const definition: IconDefinition = { name, glyphs };
    let exportName = name.replace(/-([a-z0-9])/g, (_, letter: string) => letter.toUpperCase());
    // Prefix all exports for valid, collision-free identifiers (including reserved words and digits).
    exportName = `icon${exportName[0]!.toUpperCase()}${exportName.slice(1)}`;
    catalog.push({ name, exportName, sizes: [...new Set(glyphs.map((glyph) => glyph.size))], variants: [...new Set(glyphs.map((glyph) => glyph.variant))].sort() });
    await Bun.write(join(staging, 'icons', `${name}.js`), `${header}export const ${exportName} = ${JSON.stringify(definition)};\nexport default ${exportName};\n`);
    await Bun.write(join(staging, 'icons', `${name}.d.ts`), `${header}import type { IconDefinition } from '../../types.js';\nexport declare const ${exportName}: IconDefinition & { readonly name: ${JSON.stringify(name)} };\nexport default ${exportName};\n`);
  }));
}
catalog.sort((a, b) => a.name < b.name ? -1 : 1);
await Bun.write(join(staging, 'names.js'), `${header}export {};\n`);
await Bun.write(join(staging, 'names.d.ts'), `${header}export type IconName = ${names.map((name) => JSON.stringify(name)).join(' | ')};\n`);
await Bun.write(join(staging, 'catalog.js'), `${header}export const upstreamVersion = ${JSON.stringify(upstreamPackage.version)};\nexport const glyphCount = ${sourceFiles.length};\nexport const iconCatalog = ${JSON.stringify(catalog)};\n`);
await Bun.write(join(staging, 'catalog.d.ts'), `${header}import type { IconName } from './names.js';\nimport type { IconVariant } from '../types.js';\nexport declare const upstreamVersion: string;\nexport declare const glyphCount: number;\nexport declare const iconCatalog: readonly { readonly name: IconName; readonly exportName: string; readonly sizes: readonly number[]; readonly variants: readonly IconVariant[] }[];\n`);
// Static import specifiers support code splitting in consumer bundlers and plain browsers.
await Bun.write(join(staging, 'loaders.js'), `${header}export const iconLoaders = Object.freeze({\n${names.map((name) => `  ${JSON.stringify(name)}: () => import(${JSON.stringify(`./icons/${name}.js`)}).then(module => module.default),`).join('\n')}\n});\n`);
await Bun.write(join(staging, 'loaders.d.ts'), `${header}import type { IconName } from './names.js';\nimport type { IconDefinition } from '../types.js';\nexport declare const iconLoaders: Readonly<Record<IconName, () => Promise<IconDefinition>>>;\n`);
await Bun.write(join(staging, 'metadata.json'), `${JSON.stringify({ upstreamVersion: upstreamPackage.version, families: names.length, glyphs: sourceFiles.length, fingerprint }, null, 2)}\n`);
await rm(destination, { recursive: true, force: true });
await rename(staging, destination);
console.log(`Generated ${names.length.toLocaleString()} icon families / ${sourceFiles.length.toLocaleString()} glyphs from @fluentui/svg-icons ${upstreamPackage.version}.`);
