import { resolve, join } from 'node:path';

const root = resolve(import.meta.dir, '..');
async function generate() {
  const process = Bun.spawn(['bun', 'scripts/generate.ts', '--force'], { cwd: root, stdout: 'inherit', stderr: 'inherit' });
  if (await process.exited !== 0) throw new Error('Generation failed');
}
async function hashOutput() {
  const directory = join(root, 'src/generated');
  const files = (await Array.fromAsync(new Bun.Glob('**/*').scan({ cwd: directory, onlyFiles: true }))).sort();
  const digest = new Bun.CryptoHasher('sha256');
  for (const name of files) digest.update(name.replaceAll('\\', '/')).update(await Bun.file(join(directory, name)).arrayBuffer());
  return digest.digest('hex');
}
await generate();
const first = await hashOutput();
await generate();
const second = await hashOutput();
if (first !== second) throw new Error(`Generation is not deterministic: ${first} != ${second}`);
console.log(`Every generated byte is reproducible. SHA-256: ${second}`);
